#include <stdio.h>
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.
*/


int fibonacci(){
    int first = 0;
    int second = 1;
    int next  = 0;
    int numbertimes = 10;
    int sum;

//this loops for like 10 times, refer to the variable above
    for( int i = 1; i <= numbertimes; i++){
        //ambot nganong naa ni or para unsa ni dina nako labtan kay di mo gana og ako labtan
        if(i <= 0){
            next = i;
        }
        //this is just basically kuan, the logic here is just passing the value to another variable
        // in the start next = 0 + 1
        // the first number will become 1 from 0
        //the second variable will simultaneously become 2(because of the next = first + second) from 1
        else{
            next = first + second;
            first = second;
            second = next;
        }
            if(next % 2 == 0){
                sum = next + sum;
            }
        printf("\n%d", next);
    }
    printf("\nThe total sum of all the even numbers is: %d", sum);
  
}

int main(){

    fibonacci();

    return 0;
}